config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :portfolios, only: %i[index show] do
    collection do
      get 'upload_data'
      post 'synchronize'
    end
  end

  resources :groups, defaults: { format: :json }, only: [] do
    member do
      get 'states'
    end
  end
  # Defines the root path route ("/")
  root "portfolios#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :expense_companies
  has_many :expenses, through: :expense_companies
end

app/models/expense.rb
class Expense < ApplicationRecord
  paginates_per 1

  belongs_to :portfolio
  belongs_to :expense_category
  has_many :expense_companies

  monetize :amount_cents, allow_nil: true, numericality: true
end

app/models/expense_category.rb
class ExpenseCategory < ApplicationRecord
end

app/models/expense_company.rb
class ExpenseCompany < ApplicationRecord
  belongs_to :expense
  belongs_to :company

  monetize :value_cents, allow_nil: true, numericality: true

  def issue_at_formatted
    issued_at&.strftime("%d/%m/%Y")
  end
end

app/models/member.rb
class Member < ApplicationRecord
  has_many :portfolios

  def cpf_formatted
    CPF.new(cpf).formatted
  end
end

app/models/member/record.rb
class Member::Record < ApplicationRecord
  self.table_name = 'members'

  # associations
  has_many :portfolios

  # validations
  validates :name, :ide, presence: true
  validates :cpf, presence: true, length: { is: 11 }
  validates :cpf, :ide, uniqueness: true
  validate :cpf_has_number_format

  def cpf_has_number_format
    errors.add(:cpf, "Invalid CPF Format") if cpf&.match?(/\W/)
  end
end

app/models/node_group.rb
class NodeGroup < ApplicationRecord
  # enums
  enum :kind, %i[year state]

  # relations
  has_ancestry
  has_many :portfolios

  # validations
  validates :slug, presence: true
  validates :ancestry, presence: true, if: -> { kind == NodeGroup.kinds.keys[1] }
  validate :check_if_valid_year_slug
  validate :check_if_valid_state_slug
  validate :check_if_have_identical_siblings
  validate :check_if_invalid_ancestry

  # scopes
  scope :by_states, -> { where(kind: NodeGroup.kinds['state']) }
  scope :by_years, -> { where(kind: NodeGroup.kinds['year']) }
  scope :states_by_year, -> (y_group_id) { by_states.where(ancestry: y_group_id) }

  # class methods

  def self.oldest_year
    by_years.order(:slug).first
  end

  def self.states_allowed
    [	"AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA",
      "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" ].sort.freeze
  end

  def self.start_year_allowed; 2008 end

  # objects methods

  def check_if_valid_state_slug
    return if kind == NodeGroup.kinds.keys[0]

    unless NodeGroup.states_allowed.include?(slug)
      errors.add(:slug, "Invalid Slug State")
    end
  end

  def check_if_valid_year_slug
    return if kind == NodeGroup.kinds.keys[1]

    unless (NodeGroup.start_year_allowed..Date.current.year).include?(slug.to_i)
      errors.add(:slug, "Invalid Slug Year")
    end
  end

  def check_if_have_identical_siblings
    if siblings.where.not(id: id).exists?(slug: slug)
      errors.add(:slug, "Already exists a NodeGroup with same slug")
    end
  end

  def check_if_invalid_ancestry
    return if ancestry.nil?

    errors.add(:ancestry, "Invalid Ancestry Tree") unless parent.is_root?
  end
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  paginates_per 10
  belongs_to :node_group
  belongs_to :member
  has_many :expenses
  has_many :expense_categories, through: :expenses
  has_many :expense_companies, through: :expenses

  monetize :expenses_amount_cents, allow_nil: true, numericality: true

  validates :uf, :parliamentary_number, :legislature, :legislature_code, :political_party,
            uniqueness: { scope: [:node_group_id, :member_id] }

  scope :find_by_group, -> (year_group_id, state_group_id) do
    joins(:node_group)
      .where(
        node_groups: {
          id: state_group_id,
          ancestry: year_group_id,
          kind: NodeGroup.kinds['state']
        }
      )
      .order(expenses_amount_cents: :desc)
  end

  def greater_expense_companies
    expense_companies.order(value_cents: :desc).first
  end

  def expenses_order_by_greater
    expenses.order(amount_cents: :desc).group(:id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # TODO: do not allow access to routes if you have not uploaded of data
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group

  # GET /groups/:id/states
  def states
    groups = @node_group.children.order(:slug).pluck(:slug, :id)

    render json: groups
  end

  private

  def set_group
    @node_group = NodeGroup.find(params[:id])
  end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :set_portfolio, only: %i[show]
  before_action :prepare_filter, only: %i[index]
  before_action :select_by_available_years, only: %i[index]
  before_action :select_by_allowed_states, only: %i[upload_data]

  # GET /portfolios
  def index
    @portfolios = Portfolio.find_by_group(@y_group, @s_group).page params[:page]
  end

  # GET /portfolios/:id
  def show
    @expenses = @portfolio.expenses_order_by_greater.group(:id).page params[:page]
  end

  # GET /portfolios/upload_data
  def upload_data
    @portfolio = Portfolio.new
  end

  # POST /portfolios/synchronize
  def synchronize
    filter = upload_data_params[:filter].delete_if { |f| f.empty? }
    data = upload_data_params[:data]

    respond_to do |format|
      if data.present? && Actions::DataSynchronizer.extensions_permited.include?(data.content_type)
        if Actions::DataSynchronizer.call({filter: filter, data: data})
          format.html { redirect_to portfolios_path }
        end
      else
        format.html {
          redirect_to upload_data_portfolios_path,
          alert: "O arquivo enviado, não é de um tipo de arquivo aceito!"
        }
      end
    end
  end

  private

  def set_portfolio
    @portfolio = Portfolio.find(params[:id])
  end

  def upload_data_params
    params.require(:upload_data).permit(:data, filter: [])
  end

  def filter_params
    params.require(:filter).permit(:year_id, :state_id) if params['filter']
  end

  def get_state_by_oldest_year
    state_group = NodeGroup.states_by_year(NodeGroup.oldest_year&.id).order(:slug).first
    [state_group&.parent&.id, state_group&.id]
  end

  def prepare_filter
    @y_group, @s_group = filter_params.present? ? filter_params.values : get_state_by_oldest_year
  end

  def select_by_allowed_states
    @select_by_allowed_states = NodeGroup.states_allowed
  end

  def select_by_available_years
    @select_by_available_years = NodeGroup.by_years.order(:slug).pluck(:slug, :id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def fiscal_document_url(document)
    "https://www.camara.leg.br/cota-parlamentar/nota-fiscal-eletronica?ideDocumentoFiscal=#{document}"
  end

  def image_portfolio_url(ide)
    "http://www.camara.leg.br/internet/deputado/bandep/#{ide}.jpg"
  end

  def static_file_url
    "https://dadosabertos.camara.leg.br/swagger/api.html#staticfile"
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EduTest</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <div class="container-fluid my-4">
      <div class="row justify-content-center py-2">
        <div class="col-lg-10 col-md-11">
          <div class="card shadow-sm bg-body rounded-4 border-0">
            <div class="card-body">
              <%= yield %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/portfolios/_form.html.erb
<div class="text-center">
  <h4>Selecionando arquivo!</h4>
</div>

<%= form_with(scope: :upload_data, url: synchronize_portfolios_path, data: { controller: "portfolios" }) do |form| %>
  <% if alert %>
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      <%= alert %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>

  <div class="container mb-3">
    <div class="row justify-content-center">
      <div class="col-auto">
        <p class="form-text text-center">
          Clique <%= link_to 'Aqui', static_file_url, target: '_blank' %>
          para você ter acesso aos dados abertos da Câmara dos Deputados para importar!</p>
      </div>
      <div class="col-12 d-flex flex-wrap justify-content-center align-items-center">
        <div class="col-auto m-2">
          <%= form.file_field :data, required: true %>
        </div>
        <div class="col-7 col-sm-6 col-lg-4 col-xl-3 m-2 d-flex flex-column justify-content-center">
          <%= form.label :filter, "Filtrar por Estados:", class: "form-label text-center" %>
          <%=
            form.select(
              :filter,
              options_for_select(@select_by_allowed_states),
              {},
              { class: "form-select shadow-sm rounded-3 text-center", multiple: true, size: 6 }
            )
          %>
          <div class="form-text">Use `crtl + click` para marcar ou desmarcar items.
            Caso não forneça filtros, será importado os dados de todos os Estados!</div>
        </div>
      </div>
    </div>
  </div>

  <div class="text-center pb-3 pt-2">
    <%= form.submit(
      "Importar",
      class: "btn btn-outline-dark border-0 rounded-3 shadow-sm",
      data: { portfolios_target: 'import', action: "click->portfolios#disableButton"}
    ) %>
  </div>
<% end %>

app/views/portfolios/_form_filter.html.erb
<div data-controller="form-filter" class="my-4">
  <%= form_with(scope: :filter, url: portfolios_path, method: :get, class: "form-inline") do |form| %>
    <div class="container">
      <div class="row">
        <div class="d-flex align-items-center justify-content-center">
          <div class="form-floating mx-1">
            <%= form.select(
              :year_id,
              options_for_select(@select_by_available_years),
              { include_blank: true },
              {
                class: "form-select border-0 bg-light shadow-sm rounded-4 text-center",
                id: "years_select",
                required: true,
                aria: { label: "Select year" },
                data: { form_filter_target: "years", action: "change->form-filter#remoteselect" }
              }) %>
            <label>Ano</label>
          </div>

          <div class="form-floating mx-1">
            <%= form.select(
              :state_id,
              options_for_select([]),
              { include_blank: true },
              {
                class: "form-select border-0 bg-light shadow-sm rounded-4 text-center",
                id: "states_select",
                required: true,
                aria: { label: "Select state" },
                data: { form_filter_target: "states"}
              }) %>
            <label>Estado</label>
          </div>
          <%= form.submit "Filtrar", class: "btn btn-sm btn-outline-dark border-0 mx-1 rounded-3 shadow-sm", turbo_frame: :filter_field  %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/portfolios/_import_button.html.erb
<div class="d-flex justify-content-end mb-2">
  <%= link_to(
    'Importar Arquivo',
    upload_data_portfolios_path,
    class: "btn btn-outline-dark btn-sm border-0 rounded-3 shadow-sm"
  )%>
</div>

app/views/portfolios/index.html.erb
<% if @portfolios.count.positive? %>
  <%= turbo_frame_tag :filter_field do %>
    <%= render partial: "import_button" %>

    <div class="row text-center">
      <h5>Rank de Despesas Públicas dos Parlamentares</h5>
    </div>

    <%= render partial: "form_filter" %>

    <div class="table-responsive">
      <div >
        <table class="table table-hover table-sm">
          <% group = @portfolios.first.node_group %>
          <caption><em>Lista dos Deputados do Estado <b><%= group.slug %></b>
            que mais realizaram despesas no Ano de <b><%= group.parent.slug %></b>.</em>
          </caption>

          <thead>
            <tr>
              <th scope="col"></th>
              <th scope="col">Deputado(a)</th>
              <th scope="col">CPF</th>
              <th scope="col">Total de Gastos</th>
            </tr>
          </thead>

          <tbody data-controller="portfolios">
            <% @portfolios.each do |portfolio| %>
              <tr data-action="click->portfolios#linkTo" data-portfolios-target="table" data-portfolios-url-param="<%= portfolio_path(portfolio.id) %>">
                <th scope="row"><%= "#{portfolio.position}º" %></th>
                <td><%= portfolio.member.name %></td>
                <td><%= portfolio.member.cpf_formatted %></td>
                <td><%= portfolio.expenses_amount.format %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
          </div>
      <div class="d-flex justify-content-center"><%= paginate @portfolios, window: 2 %></div>
    </div>
  <% end %>
<% else %>
  <%= turbo_frame_tag :upload_data do %>
    <div class="text-center">
      <h4 class="pt-4"> Importe um arquivo(.csv)!</h4>
      <%= link_to(
        'Selecionar Arquivo',
        upload_data_portfolios_path,
        class: "btn btn-outline-dark btn-sm m-4 shadow-sm border-0 rounded-3"
      ) %>
    </div>
  <% end %>
<% end %>

app/views/portfolios/show.html.erb
<div class="d-flex align-items-center justify-content-end mb-2">
  <%= link_to('< Voltar',
    root_path(
      params: {
        filter: { year_id: @portfolio.node_group.parent.id, state_id: @portfolio.node_group.id }
      }
    ),
    class: "btn btn-outline-dark btn-sm border-0 rounded-3 shadow-sm"
  )%>
</div>

<div class="row justify-content-center px-2 mb-3">
  <div class="col-auto border border-1 rounded-3 shadow-sm p-4">
    <div class="d-flex align-items-center">
      <%= image_tag(
        image_portfolio_url(@portfolio.member.ide),
        size: "140x173") %>
      <ul>
        <dt><p class="text-center">Portfólio do(a) Deputado(a)</p></dt>
        <dd>Nome: <%= @portfolio.member.name %></dd>
        <dd>CPF: <%= @portfolio.member.cpf_formatted %></dd>
        <dd>Número de Cadastro Federal (ide): <%= @portfolio.member.ide %></dd>
        <dd>Partido Politico: <%= @portfolio.political_party %></dd>
        <dd>UF: <%= @portfolio.uf %></dd>
        <dd>Legislatura: <%= @portfolio.legislature %></dd>
      </ul>
    </div>
    <dt> Despesa Pública de maior valor: <%= @portfolio.greater_expense_companies.value.format %> </dt>
    <dt> Referente à: <%= @portfolio.greater_expense_companies.description %></dt>
  </div>
</div>

<% @expenses.each do |expense| %>
  <ul styele="list-style-type: circle;" class="px-0">
    <dt><%= "#{expense.position}. #{expense.expense_category.description}" %> <b>(<em>TOTAL: <%= expense.amount.format %></em>)</b></dt>
    <dd>
      <div class="table-responsive">
        <table class="table table-hover table-sm">
        <caption><em>Lista de suas Despesas Públicas com <%= expense.expense_category.description %>.</em><caption>
          <thead>
            <tr>
              <th scope="col"></th>
              <th scope="col">Data de Emissão</th>
              <th scope="col">Valor Despesa</th>
              <th scope="col">Empresa Fornecedora</th>
              <th scope="col"></th>
            </tr>
          </thead>
          <tbody>
            <% expense.expense_companies.order(value_cents: :desc).each_with_index do |ec, i| %>
              <tr>
                <th scope="row"><%= "#{i.next}º" %></th>
                <td><%= ec.issue_at_formatted %></td>
                <td><%= ec.value.format %></td>
                <td><%= ec.company.name %></td>
                <td>
                  <%= link_to(
                    "NF-e",
                    fiscal_document_url(ec.ide_document),
                    class: "btn btn-outline-dark btn-sm border-0 rounded-3 shadow-sm"
                  )%>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <div class="d-flex justify-content-center"><%= paginate @expenses, window: 2 %></div>
      </div>
    </dd>
  </ul>
<% end %>

app/views/portfolios/upload_data.html.erb
<%= turbo_frame_tag :upload_data do %>
  <div class="d-flex align-items-center justify-content-end mb-2">
    <%= link_to('< Voltar', root_path, class: "btn btn-sm btn-outline-dark border-0 rounded-3 shadow-sm") %>
  </div>

  <%= render "form", portfolio: @portfolio %>
<% end %>